

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/invoice_management?serverTimezone=UTC
    username: root
    password: coen275!
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  #    jndi-name: java:jboss/datasources/customers


server:
  port: 8888

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
