

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blockchain_voting?serverTimezone=UTC
    username: root
    password: coen275!
    driver-class-name: com.mysql.jdbc.Driver

#    jndi-name: java:jboss/datasources/customers

jpa:
  properties:
    hibernate:
      hbm2ddl:
        auto: create-drop
server:
  port: 8888
